export enum RoomStatusEnum {
  AVAILABLE_FOR_BOOKING = 'AVAILABLE_FOR_BOOKING',
  STAYING = 'STAYING',
  LONG_STAYING = 'LONG_STAYING',
  OUT_OF_ORDER = 'OUT_OF_ORDER',
  RESERVED = 'RESERVED',
  BOOKED = 'BOOKED',
  MAINTENANCE = 'MAINTENANCE',
  EARLY_CHECK_IN = 'EARLY_CHECK_IN',
  LATE_CHECK_OUT = 'LATE_CHECK_OUT',
}
