export enum BookingStatusEnum {
  CREATED = 'CREATED',
  CANCELLED_BY_USER = 'CANCELLED_BY_USER',
  CONFIRMED = 'CONFIRMED',
  CONFIRMATION_TIMEOUT = 'CONFIRMATION_TIMEOUT',
  PAID = 'PAID',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  PAYMENT_TIMEOUT = 'PAYMENT_TIMEOUT',
}
