services:
  hmgs_demo_postgres:
    container_name: hmgs_demo_postgres
    image: postgres:16
    env_file:
      - .env.demo
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - hmgs_demo_postgres:/var/lib/postgresql/data
    restart: on-failure

  hmgs_demo_redis:
    container_name: hmgs_demo_redis
    image: redis:latest
    ports:
      - 6380:6379
    restart: on-failure

  hmgs_demo_app:
    container_name: hmgs_demo_app
    depends_on:
      - hmgs_demo_postgres
      - hmgs_demo_redis
    build:
      context: .
      dockerfile: docker/demo/Dockerfile
    env_file:
      - .env.demo
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    ports:
      - 5001:5000
    command: npm run start:dev:app
    restart: on-failure

  hmgs_demo_worker:
    container_name: hmgs_demo_worker
    depends_on:
      - hmgs_demo_postgres
      - hmgs_demo_redis
    build:
      context: .
      dockerfile: docker/demo/Dockerfile
    env_file:
      - .env.demo
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    command: npm run start:dev:worker
    restart: on-failure

volumes:
  hmgs_demo_postgres:
