export enum BookingStatus {
  CREATED = 'CREATED',
  CONFIRMED = 'CONFIRMED',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRMED_EXPIRED = 'CONFIRMED_EXPIRED',
  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',
}
