export enum RoomStatusEnum {
  AVAILABLE_FOR_BOOKING = 'AVAILABLE_FOR_BOOKING',
  OUT_OF_ORDER = 'OUT_OF_ORDER',
  STAYING = 'STAYING',
  LONG_STAYING = 'LONG_STAYING',
  RESERVED = 'RESERVED',
  BOOKED = 'BOOKED',
  MAINTENANCE = 'MAINTENANCE',
}
